package storage

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"github.com/thorsten-de/go-news/domain"
)

// OllamaEmbedder is an embedder that uses the Ollama API to generate embeddings.
type OllamaEmbedder struct {
	baseUrl string
	model   string
	client  *http.Client
}

var _ domain.Embedder = (*OllamaEmbedder)(nil)

// NewOllamaEmbedder creates a new OllamaEmbedder with the given base URL and model.
// If baseUrl is empty, it defaults to "http://localhost:11434".
// If model is empty, it defaults to "nomic-embed-text".
func NewOllamaEmbedder(baseUrl, model string) *OllamaEmbedder {
	if baseUrl == "" {
		baseUrl = "http://localhost:11434"
	}
	if model == "" {
		model = "nomic-embed-text"
	}
	return &OllamaEmbedder{
		baseUrl: baseUrl,
		model:   model,
		client:  &http.Client{},
	}
}

// Request structure representing Ollama's API expectations
type embedRequest struct {
	Model  string `json:"model"`
	Prompt string `json:"prompt"`
}

// Response contains the vector embedding generated by the model
type embedResponse struct {
	Embedding []float32 `json:"embedding"`
}

func (e *OllamaEmbedder) Embed(ctx context.Context, text string) ([]float32, error) {
	// Prepare the request body
	reqBody := embedRequest{
		Model:  e.model,
		Prompt: text,
	}
	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return nil, fmt.Errorf("marshal request failed: %w", err)
	}

	// Create the request. Using a context allows callers to cancel
	// long-running embedding operations.
	req, err := http.NewRequestWithContext(ctx,
		"POST",
		e.baseUrl+"/api/embeddings",
		bytes.NewBuffer(jsonData),
	)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")

	// Send the request to the Ollama API
	resp, err := e.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("ollama request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("ollama error %d: %s", resp.StatusCode, body)
	}

	// Decode the response body into the result struct
	var result embedResponse
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("decode response failed: %w", err)
	}

	return result.Embedding, nil
}
